<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Company;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Return all company manager users
     *
     * @param Company $company
     * @return \Doctrine\ORM\Query
     */
    public function getCompanyManagersQuery(Company $company)
    {
        // TODO: add select by company
        return $this->createQueryBuilder('u')
            ->andWhere('u.roles LIKE :role')
            ->setParameter('role', '%"ROLE_COMPANY_MANAGER"%')
            ->addOrderBy('u.id', 'DESC')
            ->getQuery();
    }
}
