security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_USER

        ROLE_COMPANY_ADMIN:
            - ROLE_COMPANY_MANAGER
            - ROLE_USER

        ROLE_COMPANY_MANAGER:
            - ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: authentication.handler.login_success_handler

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_DISABLED }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/company/company-managers, role: ROLE_COMPANY_ADMIN }
        - { path: ^/company/manager/, role: ROLE_COMPANY_MANAGER }
        - { path: ^/company, role: [ROLE_COMPANY_ADMIN, ROLE_COMPANY_MANAGER] }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }